### ISSUE TITLE
[ExPetrum-1.12.2-1.0.10] Game crashes when loading world

### ISSUE THREAD

**Issue by TrialDragon** [V0idWa1k3r/ExPetrum#12] opened 2018-07-30 21:27 UTC
[crash-2018-07-30_14.07.16-client.txt](https://github.com/V0idWa1k3r/ExPetrum/files/2242957/crash-2018-07-30_14.07.16-client.txt)
I get a crash whenever I attempt to create or load a world. World type doesn't matter as I've tried it on bothExPetrum and Default.

**Comment by V0idWa1k3r** [comment] 2018-07-31 08:53
I am unable to reproduce your issue with the exact same setup as far as I can tell. Could you please provide your debug.log so I can verify my setup?
I am not sure that this is related to exp. Something is passing null as the renderViewEntity but I don't touch it anywhere. Try using stable versions of mods instead of bleeding-edge alphas and see if the issue persists.

**Comment by TrialDragon** [comment] 2018-07-31 19:08
Here is the debug log which I think is correct.  Also, it must be a mod incompatibility as I finally managed to get it to run when it is by itself with absolutely no other mods.
[debug-5.log.gz](https://github.com/V0idWa1k3r/ExPetrum/files/2246739/debug-5.log.gz)

**Comment by V0idWa1k3r** [comment] 2018-07-31 19:50
Caused by: java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method) ~[?:1.8.0_171]
	at java.nio.DirectByteBuffer.<init>(Unknown Source) ~[?:1.8.0_171]
	at java.nio.ByteBuffer.allocateDirect(Unknown Source) ~[?:1.8.0_171]
You ran out of memory. Which is strange considering that you allocated 2gb which should be more than enough(I play at 1gb).

**Comment by V0idWa1k3r** [comment] 2018-08-01 18:53
Since you've fixed the issue and it looks like it was a video driver problem(info from discord) I'm closing this for now. Feel free to ask me to open this if the problem is traced down to ExPetrum.

**Closed by V0idWa1k3r** 2018-08-01 18:53 UTC
Labels: Can't reproduce, bug
